import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const appSource = await readFile(new URL("../public/app.js", import.meta.url), "utf8");
const pageSource = await readFile(new URL("../public/index.html", import.meta.url), "utf8");

test("continuous slider input updates charts without replaying trace animation", () => {
  const sliderHandler = appSource.match(/input\.addEventListener\("input",[\s\S]*?\n\s*}\);/);

  assert.ok(sliderHandler, "expected a slider input handler");
  assert.match(sliderHandler[0], /renderResult\(false\)/);
});

test("both charts position Y-axis labels to the left of the plot axis", () => {
  // These labels used to be static markup. They are now generated by
  // renderAxes() from the plotted range, so the assertion moved with them —
  // the guarantee is unchanged: Y labels sit left of the plot edge and are
  // end-anchored, on both charts.
  const renderAxes = appSource.match(/function renderAxes\([\s\S]*?\n}/);

  assert.ok(renderAxes, "expected a renderAxes function");
  assert.match(renderAxes[0], /setAttribute\("x", String\(plot\.left - \d+\)\)/);
  assert.match(renderAxes[0], /setAttribute\("text-anchor", "end"\)/);

  for (const chart of ["software", "capability"]) {
    assert.match(pageSource, new RegExp(`class="axis-labels" id="${chart}-axis"`));
  }
});

test("axis labels are derived from the data rather than hard-coded", () => {
  // A hard-coded axis silently misreports any range other than the preview's.
  assert.doesNotMatch(pageSource, /<text x="50"/, "Y labels should not be static markup");
  assert.match(appSource, /function niceTicks\(/);
});
